spring:
  application:
    name: NeoSlots
  datasource:
    url: jdbc:postgresql://localhost:5432/NeoSlots
    username: postgres
    password: 233122
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    drop-first: false

app:
  auth-service:
    url: http://localhost:8081
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:tQGRxTiCqvPrtCUo25YIio2ilZOY0/hFdIM1fSfqqBo=}
      access-exp-ms: 900000

server:
  port: 8080
